MEDIUM_TASK = {
    "task_id": "task_medium",
    "difficulty": "medium",
    "description": (
        "Classify clips with mixed or borderline evidence. "
        "Use metadata trade-offs to justify KEEP/BORDERLINE/REJECT."
    ),
    "data_corpus": [
        {
            "id": "med_001",
            "clip_id": "clip_0008",
            "duration_s": 6.2,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.24,
            "face_confidence": 0.78,
            "head_pose_yaw_deg": 14.4,
            "head_pose_pitch_deg": 9.3,
            "motion_score": 0.29,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.18,
            "mouth_open_ratio": 0.23,
            "blink_rate_hz": 0.30,
            "audio_snr_db": 18.5,
            "transcript_word_count": 20,
            "transcript_confidence": 0.75,
            "lighting_uniformity": 0.62,
            "occlusion_present": False,
            "environment_tag": "office",
            "framing": "left",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "med_002",
            "clip_id": "clip_0009",
            "duration_s": 10.6,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.23,
            "face_confidence": 0.77,
            "head_pose_yaw_deg": 16.1,
            "head_pose_pitch_deg": 9.8,
            "motion_score": 0.31,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.19,
            "mouth_open_ratio": 0.24,
            "blink_rate_hz": 0.31,
            "audio_snr_db": 17.4,
            "transcript_word_count": 23,
            "transcript_confidence": 0.73,
            "lighting_uniformity": 0.59,
            "occlusion_present": False,
            "environment_tag": "podcast_corner",
            "framing": "front",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "med_003",
            "clip_id": "clip_0010",
            "duration_s": 7.4,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.27,
            "face_confidence": 0.82,
            "head_pose_yaw_deg": 11.2,
            "head_pose_pitch_deg": 7.7,
            "motion_score": 0.24,
            "bg_complexity": "office",
            "bg_complexity_score": 0.14,
            "mouth_open_ratio": 0.29,
            "blink_rate_hz": 0.26,
            "audio_snr_db": 20.1,
            "transcript_word_count": 22,
            "transcript_confidence": 0.81,
            "lighting_uniformity": 0.66,
            "occlusion_present": False,
            "environment_tag": "workstation",
            "framing": "front",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "med_004",
            "clip_id": "clip_0011",
            "duration_s": 4.3,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.21,
            "face_confidence": 0.69,
            "head_pose_yaw_deg": 19.1,
            "head_pose_pitch_deg": 10.6,
            "motion_score": 0.39,
            "bg_complexity": "busy_room",
            "bg_complexity_score": 0.23,
            "mouth_open_ratio": 0.21,
            "blink_rate_hz": 0.34,
            "audio_snr_db": 15.0,
            "transcript_word_count": 13,
            "transcript_confidence": 0.69,
            "lighting_uniformity": 0.54,
            "occlusion_present": False,
            "environment_tag": "classroom",
            "framing": "offgaze",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "med_005",
            "clip_id": "clip_0003",
            "duration_s": 8.7,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.36,
            "face_confidence": 0.91,
            "head_pose_yaw_deg": 8.1,
            "head_pose_pitch_deg": 5.4,
            "motion_score": 0.14,
            "bg_complexity": "solid_dark",
            "bg_complexity_score": 0.08,
            "mouth_open_ratio": 0.34,
            "blink_rate_hz": 0.24,
            "audio_snr_db": 23.9,
            "transcript_word_count": 29,
            "transcript_confidence": 0.88,
            "lighting_uniformity": 0.81,
            "occlusion_present": False,
            "environment_tag": "studio",
            "framing": "front",
            "expected_label": "KEEP",
            "review_status": "pending",
        },
    ],
}
