EASY_TASK = {
    "task_id": "task_easy",
    "difficulty": "easy",
    "description": (
        "Classify clips with dominant quality evidence. "
        "Return one label in {KEEP, BORDERLINE, REJECT} with brief metadata-grounded reasoning."
    ),
    "data_corpus": [
        {
            "id": "easy_001",
            "clip_id": "clip_0001",
            "duration_s": 8.4,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.43,
            "face_confidence": 0.94,
            "head_pose_yaw_deg": 6.2,
            "head_pose_pitch_deg": 4.3,
            "motion_score": 0.09,
            "bg_complexity": "solid_dark",
            "bg_complexity_score": 0.05,
            "mouth_open_ratio": 0.36,
            "blink_rate_hz": 0.22,
            "audio_snr_db": 27.4,
            "transcript_word_count": 28,
            "transcript_confidence": 0.89,
            "lighting_uniformity": 0.88,
            "occlusion_present": False,
            "environment_tag": "studio",
            "framing": "front",
            "expected_label": "KEEP",
            "review_status": "pending",
        },
        {
            "id": "easy_002",
            "clip_id": "clip_0004",
            "duration_s": 7.1,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.38,
            "face_confidence": 0.90,
            "head_pose_yaw_deg": 7.8,
            "head_pose_pitch_deg": 5.0,
            "motion_score": 0.12,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.09,
            "mouth_open_ratio": 0.33,
            "blink_rate_hz": 0.21,
            "audio_snr_db": 24.1,
            "transcript_word_count": 24,
            "transcript_confidence": 0.86,
            "lighting_uniformity": 0.80,
            "occlusion_present": False,
            "environment_tag": "office",
            "framing": "front",
            "expected_label": "KEEP",
            "review_status": "pending",
        },
        {
            "id": "easy_003",
            "clip_id": "clip_0007",
            "duration_s": 8.0,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.25,
            "face_confidence": 0.80,
            "head_pose_yaw_deg": 17.5,
            "head_pose_pitch_deg": 8.2,
            "motion_score": 0.26,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.16,
            "mouth_open_ratio": 0.25,
            "blink_rate_hz": 0.29,
            "audio_snr_db": 19.4,
            "transcript_word_count": 19,
            "transcript_confidence": 0.76,
            "lighting_uniformity": 0.65,
            "occlusion_present": False,
            "environment_tag": "home_office",
            "framing": "front",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "easy_004",
            "clip_id": "clip_0014",
            "duration_s": 3.4,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.16,
            "face_confidence": 0.56,
            "head_pose_yaw_deg": 23.0,
            "head_pose_pitch_deg": 11.2,
            "motion_score": 0.54,
            "bg_complexity": "busy_room",
            "bg_complexity_score": 0.45,
            "mouth_open_ratio": 0.15,
            "blink_rate_hz": 0.38,
            "audio_snr_db": 11.0,
            "transcript_word_count": 8,
            "transcript_confidence": 0.44,
            "lighting_uniformity": 0.38,
            "occlusion_present": True,
            "environment_tag": "corridor",
            "framing": "offgaze",
            "expected_label": "REJECT",
            "review_status": "pending",
        },
        {
            "id": "easy_005",
            "clip_id": "clip_0016",
            "duration_s": 5.0,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.18,
            "face_confidence": 0.63,
            "head_pose_yaw_deg": 25.5,
            "head_pose_pitch_deg": 12.4,
            "motion_score": 0.47,
            "bg_complexity": "busy_indoor",
            "bg_complexity_score": 0.42,
            "mouth_open_ratio": 0.17,
            "blink_rate_hz": 0.35,
            "audio_snr_db": 13.1,
            "transcript_word_count": 10,
            "transcript_confidence": 0.51,
            "lighting_uniformity": 0.42,
            "occlusion_present": False,
            "environment_tag": "street_interview",
            "framing": "left",
            "expected_label": "REJECT",
            "review_status": "pending",
        },
    ],
}
