HARD_TASK = {
    "task_id": "task_hard",
    "difficulty": "hard",
    "description": (
        "Classify difficult clips with conflicting quality cues. "
        "Reasoning should explain trade-offs across visual and audio metadata."
    ),
    "data_corpus": [
        {
            "id": "hard_001",
            "clip_id": "clip_0012",
            "duration_s": 8.6,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.31,
            "face_confidence": 0.88,
            "head_pose_yaw_deg": 15.5,
            "head_pose_pitch_deg": 9.0,
            "motion_score": 0.43,
            "bg_complexity": "busy_room",
            "bg_complexity_score": 0.34,
            "mouth_open_ratio": 0.31,
            "blink_rate_hz": 0.33,
            "audio_snr_db": 14.2,
            "transcript_word_count": 26,
            "transcript_confidence": 0.79,
            "lighting_uniformity": 0.60,
            "occlusion_present": False,
            "environment_tag": "event_hall",
            "framing": "front",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "hard_002",
            "clip_id": "clip_0013",
            "duration_s": 6.9,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.29,
            "face_confidence": 0.73,
            "head_pose_yaw_deg": 21.8,
            "head_pose_pitch_deg": 11.0,
            "motion_score": 0.46,
            "bg_complexity": "busy_room",
            "bg_complexity_score": 0.38,
            "mouth_open_ratio": 0.22,
            "blink_rate_hz": 0.36,
            "audio_snr_db": 16.6,
            "transcript_word_count": 18,
            "transcript_confidence": 0.71,
            "lighting_uniformity": 0.49,
            "occlusion_present": False,
            "environment_tag": "street_interview",
            "framing": "offgaze",
            "expected_label": "BORDERLINE",
            "review_status": "pending",
        },
        {
            "id": "hard_003",
            "clip_id": "clip_0017",
            "duration_s": 5.6,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.22,
            "face_confidence": 0.66,
            "head_pose_yaw_deg": 18.2,
            "head_pose_pitch_deg": 9.4,
            "motion_score": 0.33,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.20,
            "mouth_open_ratio": 0.27,
            "blink_rate_hz": 0.32,
            "audio_snr_db": 20.2,
            "transcript_word_count": 19,
            "transcript_confidence": 0.79,
            "lighting_uniformity": 0.57,
            "occlusion_present": False,
            "environment_tag": "home_office",
            "framing": "left",
            "expected_label": "REJECT",
            "review_status": "pending",
        },
        {
            "id": "hard_004",
            "clip_id": "clip_0018",
            "duration_s": 11.8,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.18,
            "face_confidence": 0.64,
            "head_pose_yaw_deg": 24.4,
            "head_pose_pitch_deg": 12.1,
            "motion_score": 0.41,
            "bg_complexity": "busy_indoor",
            "bg_complexity_score": 0.41,
            "mouth_open_ratio": 0.19,
            "blink_rate_hz": 0.39,
            "audio_snr_db": 13.9,
            "transcript_word_count": 14,
            "transcript_confidence": 0.66,
            "lighting_uniformity": 0.44,
            "occlusion_present": False,
            "environment_tag": "conference_room",
            "framing": "offgaze",
            "expected_label": "REJECT",
            "review_status": "pending",
        },
        {
            "id": "hard_005",
            "clip_id": "clip_0006",
            "duration_s": 7.7,
            "fps": 25,
            "resolution": "1280x720",
            "face_area_ratio": 0.30,
            "face_confidence": 0.84,
            "head_pose_yaw_deg": 10.3,
            "head_pose_pitch_deg": 6.2,
            "motion_score": 0.25,
            "bg_complexity": "simple_room",
            "bg_complexity_score": 0.13,
            "mouth_open_ratio": 0.31,
            "blink_rate_hz": 0.24,
            "audio_snr_db": 21.1,
            "transcript_word_count": 24,
            "transcript_confidence": 0.86,
            "lighting_uniformity": 0.72,
            "occlusion_present": False,
            "environment_tag": "studio",
            "framing": "front",
            "expected_label": "KEEP",
            "review_status": "pending",
        },
    ],
}
